#construye la imagen para crear los contenedores de las instancias
FROM node

ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update
RUN apt-get update -y

RUN apt-get install nano

RUN mkdir lab5
WORKDIR /home/lab5
COPY trick.sh /home/trick.sh
RUN chmod +x /home/trick.sh
COPY ip_list.txt /home/ip_list.txt

ENTRYPOINT ["sh", "/home/trick.sh"]